### PR TITLE
fix: hide Access Tokens and User Access Control tabs from package settings if the user does not have corresponding permissions

### LINKED ISSUE #306: [FE] Adaptation to changes in qubership-apihub-backend authorization
After the security scan, it was discovered that some endpoints on the backend don't have proper authorization. It is necessary to make the relevant adaptations to the changes on the frontend.
The following authorization changes have been made on the backend:
- `GET /api/v2/roles` - now requires a system administrator role or a role with the `user_access_management` permission in any package
- `GET /api/v2/permissions` - now requires a system administrator role or a role with the `user_access_management` permission in any package
- `GET /api/v2/users` - now requires a system administrator role or a role with the `user_access_management` permission in any package
- `GET /api/v2/users/{userId}` - now requires a system administrator role or a role with the `user_access_management` permission in any package, or the userId in the request must match the userId in the token
- `GET /api/v2/packages/{packageId}/members` - changed from `read` to `user_access_management` permission
- `GET /api/v4/packages/{packageId}/apiKeys` - changed from `read` to `access_token_management` permission for workspace/group/package/dashboard-level API keys, and for system API keys, a system administrator role is required
- `GET /api/v2/packages/{packageId}/apiKeys` -  removed as the deprecation period has ended
- `POST /api/v2/packages/{packageId}/apiKeys` - removed as the deprecation period has ended
- `GET /api/v3/packages/{packageId}/apiKeys` -  removed as the deprecation period has ended
- `POST /api/v3/packages/{packageId}/apiKeys` -  removed as the deprecation period has ended

Changes have been made in the [fix_authorization ](https://github.com/Netcracker/qubership-apihub-backend/tree/fix_authorization) branch.

### PR DESCRIPTION
**Pull request by iurii-golovinskii**
…authorization

### CODE REVIEW

File: src/packages/portal/pages/PortalPage/BaseVersionPage/PackageSettingsPage/AccessControlTab.ts [hunk 1]
```diff
@@ -1,10 +1,11 @@
 import type { Page } from '@playwright/test'
 import { BaseSettingsTab } from './BaseSettingsTab'
```
Comment (iurii-golovinskii) [inline src/packages/portal/pages/PortalPage/BaseVersionPage/PackageSettingsPage/AccessControlTab.ts]: Proof: 
image

File: src/packages/portal/pages/PortalPage/BaseVersionPage/PackageSettingsPage/AccessControlTab.ts [hunk 2]
```diff
@@ -13,6 +14,7 @@ export class AccessControlTab extends BaseSettingsTab {
   readonly searchbar = new SearchBar(this.page.getByTestId('SearchUser'), 'Search User')
   readonly addUserDialog = new AcAddUserDialog(this.page)
   readonly deleteUserDialog = new BaseRemoveDialog(this.page)
+  readonly notHavePermission  = new Title(this.page.getByTestId('NotPermissionSettingsPackage'), NO_PERMISSION_PAGE)
```
Comment (vOrigins) [inline src/packages/portal/pages/PortalPage/BaseVersionPage/PackageSettingsPage/AccessControlTab.ts]: Currently, this leads to the following output in the report:

bad-placeholder

I suggest making the output like this:

good-placeholder

To do this, you need to replace `Title` with `Placeholder`, and also move it to the parent component to avoid duplication. You can also change the test ID to reflect that it's a placeholder. Something like this:

```typescript
export class PackageSettingsPage {

  readonly breadcrumbs = new Breadcrumbs(this.page.getByTestId('PackageBreadcrumbs'), 'Package settings')
  readonly title = new Title(this.page.getByTestId('ToolbarTitleTypography'), 'Package settings')
  readonly exitBtn = new Button(this.page.getByTestId('ExitButton'), 'Exit')
  readonly noPermissionPlaceholder  = new Placeholder(this.page.getByTestId('NoPermissionPlaceholder'), 'No permission')
  readonly generalTab = new GeneralSettingsTab(this.page)
  readonly apiSpecConfigTab = new ApiSpecConfigTab(this.page)
  readonly versionsTab = new VersionsTab(this.page)
  readonly accessTokensTab = new AccessTokensTab(this.page)
  readonly accessControlTab = new AccessControlTab(this.page)

  constructor(private readonly page: Page) { }
}
```

File: src/test-data/portal/uac/general/messages.ts [hunk 3]
```diff
@@ -11,3 +11,4 @@ export const NO_PERM_GEN_TOKEN = 'You do not have permission to generate token'
 export const NO_PERM_REVOKE_TOKEN = 'You do not have permission to revoke the token'
 export const NO_PERM_ADD_MEMBER = 'You do not have permission to add member'
 export const NO_PERM_MANAGE_ROLES = 'You do not have permission to manage user roles in current package'
+export const NO_PERMISSION_PAGE = 'You do not have permission to see this page'
```
Comment (vOrigins) [inline src/test-data/portal/uac/general/messages.ts]: Perhaps `NO_PERM_SEE_PAGE` would be more suitable in accordance with other variables.

File: src/tests/portal/03-access-control/3.1.1-viewer-package.spec.ts [hunk 4]
```diff
@@ -261,31 +259,15 @@ test.describe('03.1.1 Access Control. Viewer role. (Package)', () => {
...
-        await accessTokensTab.generateBtn.hover({ force: true })
-
-        await expect(portalPage.tooltip).toHaveCount(1)
-        await expect(portalPage.tooltip).toHaveText(NO_PERM_GEN_TOKEN)
-
-        await expect(portalPage.tooltip).toHaveCount(1)
-        // await expect(portalPage.tooltip).toHaveText(NO_PERM_REVOKE_TOKEN) //TODO: TestCase-B-1019
+        await expect(accessTokensTab).toHaveCount(0)
+        await portalPage.gotoPackage(testPackage, SETTINGS_TAB_TOKENS)
+        await expect(accessTokensTab.notHavePermission).toHaveText(NO_PERMISSION_PAGE)
```
Comment (vOrigins) [inline src/tests/portal/03-access-control/3.1.1-viewer-package.spec.ts]: This is how you can change the code so that the report matches the first comment.

```typescript
      await expect(accessControlTab).not.toBeVisible()

      await portalPage.gotoPackage(testPackage, SETTINGS_TAB_TOKENS)

      await expect(noPermissionPlaceholder).toBeVisible()
      await expect(noPermissionPlaceholder).toHaveText(NO_PERMISSION_PAGE)
```

Perhaps checking the specific message is even unnecessary; it might be enough to check that the placeholder is displayed.
You can also separate actions and expectations with empty lines to maintain consistency.

**Review by vOrigins — CHANGES_REQUESTED** [review]

**Review by vOrigins — APPROVED** [review]

**Review by JayLim2 — APPROVED** [review]
